name: Actualizar Dividendos Diarios

on:
  schedule:
    - cron: '0 10 * * 1-5'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: |
          pip install requests

      - name: Ejecutar Scraper
        run: |
          python scraper.py

      - name: Guardar cambios
        run: |
          git config --global user.name "DividendBot"
          git config --global user.email "bot@dividendos.com"
          git add index.html
          git commit -m "Actualizacion automatica de dividendos" || echo "Sin cambios"
          git push
